### ISSUE TITLE
Mysticism can be bought with negative cost

### ISSUE THREAD

**Issue by asheiduk** [tsjensen/civbuddy#5]
Steps to reproduce:
- Buy Astronomy, Coinage and Medicine.
- Enter "50" points in "Funds"
- Mark ("?") Engineering (cost: 140-3*20=80)

Now Mysticism is shown with cost "-30". The "Funds" shows "50(80)" with "50" in red.
- Mark Mysticism

Now "Funds" shows "50(50)" in green.

Summary: Buying Mysticism does not only attribute the green bonuses for both Engineering and Mysticism, it also gives you more bonus then Mysticism costs. This surplus spills over to Engineering.

**Comment by tsjensen** [comment]
Interesting. On my Chrome on iPhone with iOS 9, I can reproduce the first part of the bug (Mysticism showing as -30 / 30). So it's a bug already.
However, the second part does not happen: Funds show as just "50" without green parts, and stay that way even when I mark Mysticism. Subsequent marking of Engineering correctly gives "50 (80)" (red/green), because Mysticism is free.

**Comment by asheiduk** [comment]
Mysticism is free. But Engineering still costs `140 - 60 = 80` and `80 != 50`. With only 50 Funds you should not be able to buy Engineering then. 

And please note: The order you mark Engineering and Mysticism is important! Marking first M then E indeed has the correct behaviour (regarding to "Fund" number)

**Comment by tsjensen** [comment]
Understood; I missed the order thing.
When first marking Engineering, you do get a warning that it's too expensive, right?
After marking Mysticism (-30), it's falsely considered OK again.

**Comment by asheiduk** [comment]
Exactly :-)

**Comment by tsjensen** [comment]
Fixed, I hope.
This appeared to be quite easy. In fact, there was a 'fixme' comment in the code already :-)

**Comment by asheiduk** [comment]
I'v tried v0.6 build 80 and I can still get that behaviour:
- Switch "Funds" to "off"
- Buy ASTRONOMY, COINAGE, MEDICINE.
- Select ENGINEERING
- Switch "FUnds" to "on" and enter 50
- Switch back, ignore warning about insufficient funds.

MYSTICISM has -30 cost now.

**Comment by tsjensen** [comment]
Didn't release yet. The new Gradle Build is still missing the deploy feature ... stay tuned.

**Comment by tsjensen** [comment]
Released. :smile:
